# Create your pod here
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod
  labels:
    project: kubernetes-project
spec: 
  containers:
    - name: kubernetes-pod
      image: nimesh25/flask-app:v1.2-using-cache 
      ports:
        - containerPort: 31111
